# Generated by Django 3.2.9 on 2022-01-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_main', models.BooleanField()),
                ('article_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='articles',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Article'),
        ),
    ]
