# Generated by Django 3.2.9 on 2022-01-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220103_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relationship', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
