# Generated by Django 3.2.9 on 2022-01-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220103_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Object'),
        ),
    ]
