# Generated by Django 3.2.9 on 2022-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220103_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='section_id',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relationship', to='articles.Object'),
        ),
    ]
