# Generated by Django 3.2.9 on 2022-01-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220104_0252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='Scope',
        ),
        migrations.RenameModel(
            old_name='Object',
            new_name='Tag',
        ),
    ]
