# Generated by Django 3.2.9 on 2022-01-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ForeignKey(null='null', on_delete=django.db.models.deletion.CASCADE, to='articles.scope'),
            preserve_default='null',
        ),
    ]
