# Generated by Django 3.2.9 on 2022-01-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20220107_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null='null', through='articles.Scope', to='articles.Tag'),
            preserve_default='null',
        ),
    ]
