# Generated by Django 3.2.9 on 2022-01-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_tags_article_tagsdsfg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tagsdsfg',
            new_name='tags',
        ),
    ]
