# Generated by Django 3.2.9 on 2022-01-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20220116_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
    ]
