# Generated by Django 3.2.9 on 2022-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='article_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Tag'),
        ),
    ]
