# Generated by Django 3.2.9 on 2021-11-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('image', models.TextField()),
                ('release_date', models.TextField()),
                ('lte_exists', models.TextField()),
            ],
        ),
    ]
